arch:
  - arm64-graviton2
dist: focal
  
language: python
install: skip
script: python ./src/hello.py

jobs:
#  include:
#   - arch: arm64-graviton2
#   - os: linux
#   - dist: focal
#   - virt: lxd
#jobs:
#  include:
#     - dist: xenial
#     - arch: arm64-graviton2
#       before_install:
#         - dpkg-query -s git
#         - dpkg-query -s mysql ?
#         - dpkg-query -s redis
#         - dpkg-query -s postgresql
#    - dist: focal
#      services:
#        - redis
#        - mysql
#    - dist: focal
#      addons:
#        apt:
#          sources:
#            - sourceline: "deb https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse"
#          packages:
#            - mongodb
#    - dist: focal
#      python: "2.7"
#    - dist: focal
#      python: "3.6"
#   - os: linux
#     arch: arm64 # ARMv8
#     dist: bionic
#     language: python
#     python: "3.6"
#   - os: linux
#     arch: arm64 # ARMv8
#     language: python
#     python: "2.7"
#     dist: xenial

