language: python
install: skip
script: python ./src/hello.py

jobs:
  include:
    - dist: focal
      python: "2.7"
    - dist: focal
      python: "3.6"
#   - os: linux
#     arch: arm64 # ARMv8
#     dist: bionic
#     language: python
#     python: "3.6"
#   - os: linux
#     arch: arm64 # ARMv8
#     language: python
#     python: "2.7"
#     dist: xenial

